name: CI/CD Pipeline for ASP.NET Core

on:
  push:
    branches:
      - master  # Trigger for pushes to master branch
  pull_request:
    branches:
      - master  # Trigger for PRs to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2  # Correctly formatted URL

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v2  # Correctly formatted URL
        with:
          dotnet-version: '8.0'  # Set the .NET version for your app

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the application
      - name: Build the application
        run: dotnet build --configuration Release

      # Publish the application
      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      # Upload the published files using the full URL
      - name: Upload published files
        uses: https://github.com/actions/upload-artifact@v2  # Full URL to the action
        with:
          name: myapp-publish-artifact
          path: ./publish

      # Alternatively, upload files to GitHub Release (if the previous method fails)
      - name: Upload to GitHub Release (Alternative method)
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
