name: CI/CD Pipeline for ASP.NET Core

on:
  push:
    branches:
      - master  # Trigger for pushes to master branch
  pull_request:
    branches:
      - master  # Trigger for PRs to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Set the .NET version for your app

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the application
      - name: Build the application
        run: dotnet build --configuration Release

      # Publish the application
      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      # Upload the published files as an artifact (using v2)
      - name: Upload published files
        uses: actions/upload-artifact@v2  # Using stable v2 version
        with:
          name: myapp-publish-artifact
          path: ./publish
